### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by Tails6198**
fixed framewor lol

### CODE REVIEW

**Comment by frozensnowy** [comment]
Thank you so much for fixing this major bug! I am so thankful!

**Comment by frozensnowy** [comment]
The next generation in pull requests!

**Comment by frozensnowy** [comment]
I'm debating whether or not to merge it, what if it causes issues upstream? We don't know, this needs more thorough testing.

**Comment by Tails6198** [comment]
i really think unnecessary white space characters will terribly worsen the performance of this software

**Comment by Tails6198** [comment]
this clarifies things 👍 thank you

**Pull request merged**
